# Generated by Django 4.2.5 on 2023-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
